import type { TargetAdapter, RenderedFile, RenderInput } from "./types.js";

export const codexAdapter: TargetAdapter = {
  id: "codex",
  outDir: "codex",
  render(input): RenderedFile[] {
    const files: RenderedFile[] = [];
    files.push({ path: "AGENTS.md", contents: buildAgentsMd(input) });
    for (const c of input.commands) {
      files.push({
        path: `AGENTS-commands/${c.id}.md`,
        contents: `# ${c.title}\n\n${c.body.trimStart()}`,
      });
    }
    return files;
  },
};

function buildAgentsMd({ skills, commands }: RenderInput): string {
  const lines: string[] = [];
  lines.push("# AGENTS.md");
  lines.push("");
  lines.push("> Generated by `impeccable-react`. Do not edit by hand.");
  lines.push("");
  lines.push("This file is the single entry point for AI agents working in this");
  lines.push("repository. It bundles the active skills, the command catalog, and");
  lines.push("the anti-pattern library.");
  lines.push("");

  lines.push("## Skills");
  lines.push("");
  for (const s of skills) {
    lines.push(`### ${s.name} (\`${s.id}\`)`);
    lines.push("");
    lines.push(s.summary);
    lines.push("");
    lines.push(s.body.trim());
    lines.push("");

    if (s.references.length > 0) {
      lines.push(`#### References — ${s.id}`);
      lines.push("");
      for (const r of s.references) {
        lines.push(`- **${r.id}** — ${r.summary}`);
      }
      lines.push("");
    }

    if (s.antiPatterns.length > 0) {
      lines.push(`#### Anti-patterns — ${s.id}`);
      lines.push("");
      for (const ap of s.antiPatterns) {
        const detector = ap.detector_rule ? ` (detector: \`${ap.detector_rule}\`)` : "";
        lines.push(`- **${ap.id}** [${ap.severity}]${detector} — ${ap.summary}`);
      }
      lines.push("");
    }
  }

  lines.push("## Commands");
  lines.push("");
  for (const c of commands) {
    lines.push(`### \`${c.slug}\` — ${c.title}`);
    lines.push("");
    if (c.inputs.length > 0) {
      lines.push("**Inputs:** " + c.inputs.map((i) => `\`${i.name}\` (${i.kind}${i.required ? ", required" : ""})`).join(", "));
      lines.push("");
    }
    if (c.uses_skills.length > 0) {
      lines.push("**Uses skills:** " + c.uses_skills.map((id) => `\`${id}\``).join(", "));
      lines.push("");
    }
    lines.push(c.body.trim());
    lines.push("");
  }

  return lines.join("\n");
}
